language: r
r: bioc-devel

sudo: false
cache: packages

warnings_are_errors: false

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

bioc_packages:
  - BiocInstaller

addons:
  apt:
    packages:
      - fftw3-dev
      