language: r
r: bioc-devel

sudo: false
cache: packages

warnings_are_errors: false

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

bioc_packages:
  - BiocInstaller

addons:
  apt:
    packages:
      - fftw3-dev

# https://stackoverflow.com/questions/45742068/travis-failing-for-r-bioc-packages-using-new-latex-format
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpng-dev
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix


